/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as CategoriesCategoryRouteImport } from './routes/categories/$category'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRoute
  '/cart': typeof CartRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/unauthorized'
    | '/categories/$category'
    | '/products/$productId'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/products'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/unauthorized'
    | '/categories/$category'
    | '/products/$productId'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/products'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/cart'
    | '/unauthorized'
    | '/categories/$category'
    | '/products/$productId'
    | '/categories/'
    | '/checkout/'
    | '/favorites/'
    | '/products/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRoute
  CartRoute: typeof CartRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRoute,
  CartRoute: CartRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
